// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shardion.Terrabreak.Services.Database;

#nullable disable

namespace Shardion.Terrabreak.Migrations
{
    [DbContext(typeof(TerrabreakDatabaseContext))]
    [Migration("20251030050603_ShusoDivineReunion")]
    partial class ShusoDivineReunion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107");

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.ToTable("BagEntry");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ShusoDivineReunion.Player.DiscordPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ribbons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShieldId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DiscordPlayer");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ShusoDivineReunion.Takeover.SdrChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TakenOver")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.ToTable("SdrChannel");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ShusoDivineReunion.Takeover.SdrServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PassagesUnlocked")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TakenOver")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("SdrServer");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.HasOne("Shardion.Terrabreak.Features.Bags.Bag", "Bag")
                        .WithMany("Entries")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ShusoDivineReunion.Player.DiscordPlayer", b =>
                {
                    b.OwnsOne("Shardion.Terrabreak.Features.ShusoDivineReunion.Player.EnemyRecord", "StrongestEnemy", b1 =>
                        {
                            b1.Property<Guid>("DiscordPlayerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EnemyId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<ulong>("SourceChannelId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DiscordPlayerId");

                            b1.ToTable("DiscordPlayer");

                            b1.WithOwner()
                                .HasForeignKey("DiscordPlayerId");
                        });

                    b.Navigation("StrongestEnemy");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
