// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shardion.Terrabreak.Services.Database;

#nullable disable

namespace Shardion.Terrabreak.Migrations
{
    [DbContext(typeof(TerrabreakDatabaseContext))]
    [Migration("20260324063250_ZgeSelectedLoadoutIdAsInt")]
    partial class ZgeSelectedLoadoutIdAsInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.ToTable("BagEntry");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ZannotGoodenough.Player.DiscordPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquippedLoadout")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Loadout1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Loadout2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Loadout3Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UnlockedMonsterIdentifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UnlockedRelicIdentifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.HasIndex("Loadout1Id");

                    b.HasIndex("Loadout2Id");

                    b.HasIndex("Loadout3Id");

                    b.ToTable("DiscordPlayer");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Monster1Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Monster2Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Monster3Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic1Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic2Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic3Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic4Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic5Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relic6Identifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loadout");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.HasOne("Shardion.Terrabreak.Features.Bags.Bag", "Bag")
                        .WithMany("Entries")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ZannotGoodenough.Player.DiscordPlayer", b =>
                {
                    b.HasOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout1")
                        .WithMany()
                        .HasForeignKey("Loadout1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout2")
                        .WithMany()
                        .HasForeignKey("Loadout2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout3")
                        .WithMany()
                        .HasForeignKey("Loadout3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout1");

                    b.Navigation("Loadout2");

                    b.Navigation("Loadout3");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
