// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shardion.Terrabreak.Services.Database;

#nullable disable

namespace Shardion.Terrabreak.Migrations
{
    [DbContext(typeof(TerrabreakDatabaseContext))]
    partial class TerrabreakDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.ToTable("BagEntry");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ZannotGoodenough.Player.DiscordPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquippedLoadoutIndex")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("UnlockedMonsterIdentifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UnlockedRelicIdentifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.ToTable("DiscordPlayer");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.BagEntry", b =>
                {
                    b.HasOne("Shardion.Terrabreak.Features.Bags.Bag", "Bag")
                        .WithMany("Entries")
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.ZannotGoodenough.Player.DiscordPlayer", b =>
                {
                    b.OwnsOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout1", b1 =>
                        {
                            b1.Property<Guid>("DiscordPlayerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic4Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic5Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic6Identifier")
                                .HasColumnType("TEXT");

                            b1.HasKey("DiscordPlayerId");

                            b1.ToTable("DiscordPlayer");

                            b1.WithOwner()
                                .HasForeignKey("DiscordPlayerId");
                        });

                    b.OwnsOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout2", b1 =>
                        {
                            b1.Property<Guid>("DiscordPlayerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic4Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic5Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic6Identifier")
                                .HasColumnType("TEXT");

                            b1.HasKey("DiscordPlayerId");

                            b1.ToTable("DiscordPlayer");

                            b1.WithOwner()
                                .HasForeignKey("DiscordPlayerId");
                        });

                    b.OwnsOne("Shardion.Terrabreak.Features.ZannotGoodenough.Player.Loadout", "Loadout3", b1 =>
                        {
                            b1.Property<Guid>("DiscordPlayerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Monster3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic1Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic2Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic3Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic4Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic5Identifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Relic6Identifier")
                                .HasColumnType("TEXT");

                            b1.HasKey("DiscordPlayerId");

                            b1.ToTable("DiscordPlayer");

                            b1.WithOwner()
                                .HasForeignKey("DiscordPlayerId");
                        });

                    b.Navigation("Loadout1")
                        .IsRequired();

                    b.Navigation("Loadout2")
                        .IsRequired();

                    b.Navigation("Loadout3")
                        .IsRequired();
                });

            modelBuilder.Entity("Shardion.Terrabreak.Features.Bags.Bag", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
